POST http://127.0.0.1:5000/create_assistant
Content-Type: application/json

{
    "name":"test-assistant",
    "instruction":"You are a debt specialist. You will ask the following details to the customer: Name, SSN, DOB. You have to ask these details sequentially, one at a time.also you need to initiate the chat",
    "model":"gpt-4o"
}

###

POST http://127.0.0.1:5000/create_thread
Content-Type: application/json

{

}

###

POST http://127.0.0.1:5000/chat
Content-Type: application/json

{
    "thread_id":"thread_7rFcQSls5TFmJkHUYikU02qG",
    "message":""
}

###
GET https://api.openai.com/v1/threads/thread_7rFcQSls5TFmJkHUYikU02qG/runs/run_1299daPvBmSm36OyOuHejpYo
Authorization: Bearer 
OpenAI-Beta: assistants=v2

###

POST http://127.0.0.1:5000/chat
Content-Type: application/json

{
    "thread_id":"thread_8XsCoJ0tEu7x54Q2X4Jwaear",
    "message":"retry the tool call it failed earlier"
}

###
get https://api.openai.com/v1/threads/thread_8XsCoJ0tEu7x54Q2X4Jwaear/runs
Authorization: Bearer 
OpenAI-Beta: assistants=v2

###
get https://api.openai.com/v1/threads/thread_8XsCoJ0tEu7x54Q2X4Jwaear/messages
Authorization: Bearer 
OpenAI-Beta: assistants=v2

###
get http://127.0.0.1:5000/threads/thread_8XsCoJ0tEu7x54Q2X4Jwaear/messages
Content-Type: application/json

###
POST http://127.0.0.1:5000/update_assistant
Content-Type: application/json

{
    "asst_id":"asst_wIShH4GC8Fi0QClxmIij447J",
    "name":"test-assistant-7",
    "instruction":"You are a debt specialist. You will ask the following details to the customer: Name, SSN, DOB. You have to ask these details sequentially, one at a time.also you need to initiate the chat",
    "model":"gpt-4o"
}


